server:
  port: 8888
spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Automatic-receipt-processing/Backend
#          search-paths: config/**
          default-label: JUN-2